# basic
title: 绎梦机
subtitle: 有限的记忆，无限的梦
favicon: 

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: https://rmt.dogedoge.com/fetch/kurumit3/storage/avatar.jpg?fmt=webp

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  home: .
  archive: archives
  # about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/kurumiT3
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href=>/a></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
